---
development:
  cloud_name: dhgxwouqe
  api_key: '599158717924951'
  api_secret: kb7DLvJc6qxLTAh0fCAIgnQmAZ0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dhgxwouqe
  api_key: '599158717924951'
  api_secret: kb7DLvJc6qxLTAh0fCAIgnQmAZ0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dhgxwouqe
  api_key: '599158717924951'
  api_secret: kb7DLvJc6qxLTAh0fCAIgnQmAZ0
  enhance_image_tag: true
  static_image_support: false
